name: Deploy to Hostinger VPS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          node-version: '20.x'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /root/P2CARE && ./.script/deploy.sh"

    - name: Install Dependencies
      run: |
        git pull origin main
        cd USER
        npm install
        cd ..
        cd BACKEND
        npm install
        cd ..
        cd ADMIN
        npm install
        cd ..

    - name: Build and Deploy
      run: |
        cd BACKEND
        pm2 start npm --name \"test_server\" --start
        cd ..
        cd USER
        npm run build
        cd ..
        cd ADMIN
        npm run build
        cd ..
        
